#
# Module manifest for module 'PSModuleQuantityAnalyzer'
#
# Generated by: Holger Zimmermann
#
# Generated on: 2026-03-14
#

@{
    RootModule        = 'PSModuleQuantityAnalyzer.psm1'
    ModuleVersion     = '2026.3.22.1040'
    GUID              = 'a5c1c2d4-1b11-4d55-b2d3-1d9a0e8b2f11'

    Author            = 'zimmermann.holger@live.de'
    CompanyName       = 'Community'
    Copyright         = '(c) 2026 Holger Zimmermann'

    Description       = "PSModuleQuantityAnalyzer is a PowerShell module that performs static analysis of PowerShell modules and`n               generates quantitative metrics about their structure, maintainability, and architecture."

    PowerShellVersion = '5.1'

    FunctionsToExport = @(
        "Get-PSModuleQuantity",
        "Get-PSModuleSummary",
        "Get-PSModuleMetrics",
        "Get-PSModuleHealth",
        "Get-PSModuleDuplicateFunctions",
        "Get-PSModuleLargestFunctions",
        "Get-PSModuleDocumentationCoverage",
        "Get-PSModuleDependencyGraph",
        "Get-PSModuleComplexity",
        "Get-PSModuleUnusedPrivateFunctions",
        "Get-PSModuleRefactoringCandidates",
        "Export-PSModuleQuantityReport",
        "Export-PSModuleMarkdownReport"
    )

    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()

    PrivateData       = @{
        PSData = @{
            Tags         = @('PowerShell', 'Module', 'Metrics', 'Analysis', 'Maintainability', 'Code Quantity')
            ProjectUri   = 'https://github.com/HerrHozi/PSModuleQuantityAnalyzer'
            LicenseUri   = 'https://github.com/HerrHozi/PSModuleQuantityAnalyzer/blob/main/LICENSE'
            IconUri      = 'https://raw.githubusercontent.com/HerrHozi/PSModuleQuantityAnalyzer/main/Assets/icon.png'
            LastUpdate   = '2026-03-22'
            ReleaseNotes = '            
v2026.3.22.1040 - Updated PSModuleQuantityAnalyzer to version 2026.3.22.1040.
		- Minor bug fixes and performance improvements.
        
v2026.3.14.420 - Initial release of PSModuleQuantityAnalyzer on PS Gallery.
		- Added Export-PSModuleQuantityReport to export module metrics to a JSON file.
        - Added Export-PSModuleMarkdownReport to export module metrics to a Markdown file.
        
v2026.3.11.1221 - First PSModuleQuantityAnalyzer version with core functionality for analyzing PowerShell modules and generating quantitative metrics.
		- Added Get-PSModuleQuantity to calculate basic metrics like number of functions, lines of code, and cyclomatic complexity.
        - Added Get-PSModuleSummary to provide a high-level overview of module metrics.
        - Added Get-PSModuleMetrics to generate detailed metrics for each function in the module.
        - Added Get-PSModuleHealth to assess the overall health of the module based on various criteria.
        - Added Get-PSModuleDuplicateFunctions to identify duplicate functions within the module.
        - Added Get-PSModuleLargestFunctions to list the largest functions by lines of code.' 
        }
    }
}